name: Bug report
description: Submit a bug report
assignees: ["devpelux"]
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill all the info below.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Put a clear and concise description of the bug, and how to reproduce, add screenshots if are useful.
        Add some examples, with example code, if possible.
    validations:
      required: true
  - type: dropdown
    id: release
    attributes:
      label: Affected releases
      description: Select the releases affected.
      options:
        - Developing
        - 1.5.1
        - 1.5.0
        - 1.4.2
        - 1.4.1
        - 1.4.0
        - 1.3.0
        - 1.2.4
        - 1.2.3
        - 1.2.2
        - 1.2.1
        - 1.2.0
        - 1.1.2
        - 1.1.1
        - 1.1.0
        - 1.0.2
        - 1.0.1
        - 1.0.0
      multiple: true
    validations:
      required: true
  - type: dropdown
    id: net
    attributes:
      label: Framework
      description: Select the .NET release that you are using.
      options:
        - .NET 5
        - .NET 6
        - Other
      multiple: true
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: OS
      description: Specify the operative system that you are using.
      placeholder: Windows 11
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: "Code of Conduct & guidelines"
      description: >
        By submitting this issue, you agree to follow the [Code of Conduct](https://github.com/devpelux/fullcontrols/blob/main/CODE_OF_CONDUCT.md)
        and the [Contributing](https://github.com/devpelux/fullcontrols/blob/main/CONTRIBUTING.md) guidelines.
      options:
        - label: I have read and agree with the Code of Conduct and Contributing guidelines.
          required: true
