name: Bug report
description: Submit a bug report
assignees: ["devpelux"]
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill all the info below.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Put a clear and concise description of the bug, and how to reproduce, add screenshots if are useful.
        Add some examples, with example code, if possible.
    validations:
      required: true
  - type: input
    id: release
    attributes:
      label: Affected release
      description: Specify the release affected.
      placeholder: 1.0.0
    validations:
      required: true
  - type: dropdown
    id: net
    attributes:
      label: Framework
      description: Select the .NET release that you are using.
      options:
        - .NET 5
        - .NET 6
        - .NET 7
        - Other
      multiple: true
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: OS
      description: Specify the operative system that you are using.
      placeholder: Windows 11
    validations:
      required: false
