name: Feature request
description: Submit a feature request
assignees: ["devpelux"]
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill all the info below.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Put a clear and concise description of the feature, if is related to a problem, add screenshots if are useful.
        Add some examples, with example code, if are useful.
    validations:
      required: true
